SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO R
WHERE (FOOD_TYPE, FAVORITES) IN (
    SELECT FOOD_TYPE, MAX(I.FAVORITES)
    FROM REST_INFO I
    GROUP BY I.FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC;