WITH ECOL_V AS (
    SELECT ID, 
    ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) AS ROW_N
    FROM ECOLI_DATA
    ORDER BY SIZE_OF_COLONY DESC
)

SELECT ECOLI_DATA.ID,
    IF(
    ROW_N / (SELECT COUNT(*) FROM ECOLI_DATA) <= 0.25, 'CRITICAL',
    IF(
    ROW_N / (SELECT COUNT(*) FROM ECOLI_DATA) <= 0.5, 'HIGH',
    IF(
    ROW_N / (SELECT COUNT(*) FROM ECOLI_DATA) <= 0.75, 'MEDIUM', 'LOW'
    ))) COLONY_NAME
FROM ECOLI_DATA
JOIN ECOL_V on ECOLI_DATA.ID = ECOL_V.ID
ORDER BY ID