SELECT YEAR, MONTH, GENDER, COUNT(*) USERS
FROM (SELECT DISTINCT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, GENDER, U.USER_ID
FROM USER_INFO U
JOIN ONLINE_SALE O on U.USER_ID = O.USER_ID
WHERE GENDER IS NOT NULL) DATAS
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER