SELECT
YEAR(SALES_DATE),
MONTH(SALES_DATE),
COUNT(DISTINCT USER_INFO.USER_ID) AS PUCHASED_RATIO,
ROUND(COUNT(DISTINCT USER_INFO.USER_ID) /
      (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) <= 2021)
    , 1) AS PUCHASED_RATIO

FROM USER_INFO
JOIN ONLINE_SALE ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID
WHERE YEAR(JOINED) <= 2021 
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR(SALES_DATE) DESC, MONTH(SALES_DATE)
LIMIT 1000