-- 코드를 입력하세요
SELECT CAR_ID, IF(CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' >= START_DATE AND
          '2022-10-16' <= END_DATE
    GROUP BY CAR_ID
), '대여중', '대여 가능') AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;

