-- 코드를 입력하세요

SELECT F.FLAVOR
FROM FIRST_HALF F
INNER JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER FROM JULY GROUP BY FLAVOR) J ON F.FLAVOR = J.FLAVOR
order by F.TOTAL_ORDER + J.TOTAL_ORDER desc limit 3