WITH RECURSIVE HOURS AS (
  SELECT 0 AS HOUR
  UNION ALL
  SELECT HOUR + 1 FROM HOURS
  WHERE HOUR < 23
)

SELECT HOURS.HOUR HOUR, IF((COUNT IS NOT NULL), COUNT, 0) COUNT
FROM HOURS
LEFT JOIN (SELECT HOUR(DATETIME) HOUR, COUNT(*) COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
    ORDER BY HOUR) VALUE on HOURS.HOUR = VALUE.HOUR