-- 코드를 작성해주세요
SELECT EMP_NO, EMP_NAME,
    IF(AVG(SCORE) >= 96, 'S',
      IF(AVG(SCORE) >= 90, 'A',
        IF(AVG(SCORE) >= 80, 'B', 'C'))) GRADE,
    IF(AVG(SCORE) >= 96, SAL / 100 * 20,
      IF(AVG(SCORE) >= 90, SAL / 100 * 15,
        IF(AVG(SCORE) >= 80, SAL / 100 * 10, 0))) BONUS
FROM HR_DEPARTMENT 
NATURAL JOIN HR_EMPLOYEES
NATURAL JOIN HR_GRADE
GROUP BY EMP_NO
ORDER BY EMP_NO