-- 코드를 작성해주세요
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (SELECT DISTINCT ITEM_TREE.ITEM_ID
FROM ITEM_INFO
JOIN ITEM_TREE on PARENT_ITEM_ID = ITEM_INFO.ITEM_ID
WHERE RARITY LIKE 'RARE')

ORDER BY ITEM_ID DESC