-- 코드를 작성해주세요
WITH CsVAL AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME LIKE 'C#'
), PyVAL AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME LIKE 'Python'
)

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS, CsVAL, PyVAL
WHERE SKILL_CODE & CsVAL.CODE > 0 OR
    SKILL_CODE & PyVAL.CODE > 0
ORDER BY ID