-- 코드를 작성해주세요
WITH BIGGEST AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)   
)

SELECT YEAR, BIGGEST.SIZE - SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA
JOIN BIGGEST ON YEAR(DIFFERENTIATION_DATE) = BIGGEST.YEAR
ORDER BY YEAR, YEAR_DEV
