-- 코드를 작성해주세요
WITH EDITED AS (
    SELECT FISH_TYPE, IF(LENGTH IS NULL, 10, LENGTH) LENGTH
    FROM FISH_INFO
)

SELECT COUNT(*) FISH_COUNT, (SELECT MAX(LENGTH) FROM FISH_INFO WHERE FISH_INFO.FISH_TYPE = EDITED.FISH_TYPE) MAX_LENGTH, FISH_TYPE
FROM EDITED
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33

ORDER BY FISH_TYPE